---
title: " "
pagetitle: "Joaquín Martínez Minaya"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

<div align="justify">
## Supplementary material for papers

### 2023

- **INLAComp project**

  - Manuscript [A flexible Bayesian tool for CoDa mixed models: logistic-normal distribution with Dirichlet covariance](https://arxiv.org/abs/2308.13928)
  
  - R-Code: [INLAComp](https://github.com/jmartinez-minaya/INLAcomp)
  
  - Tutorials:

    1. [Fitting LNDMs with fixed effects](https://github.com/hrue/r-inla/commit/3577c1b030a8460ff7194893bd97e57a62a1399d)
    2. [Fitting Spatial LNDMs. A simulation](supplementary/INLAComp/simulations.html)
    3. [Fitting LNDMs with fixed and random effects. A real problem](supplementary/INLAComp/my-vignette.html)
    
---


- **dirinla project**
  
  - Manuscript: [The integrated Nested Laplace Approximation for fitting Dirichlet regressions](https://www.tandfonline.com/doi/full/10.1080/10618600.2022.2144330) or [arxiv link](https://arxiv.org/abs/1907.04059)
  
  - R-Code: [dirinla](https://inlabru-org.r-universe.dev/dirinla)
  
  - Tutorials:
    1. [Fitting Dirichlet regression with fixed effects](supplementary/CODA/fixed/my-vignette_fixed.html)
    2. [Fitting Dirichlet regression with random effects](supplementary/CODA/fixed/my-vignette_fixed.html)
    3. [Simulation results using fixed and i.i.d. random effects](supplementary/CODA/tests.html)


### 2021 

- **Plant's epidemiology**

  - Manuscript: [Modeling Inoculum Availability of Plurivorosphaerella nawae in Persimmon Leaf Litter with Bayesian Beta Regression](https://apsjournals.apsnet.org/doi/10.1094/PHYTO-08-20-0359-R)
  
  - R-Code: [betapathogen](https://bitbucket.org/joaquin-martinez-minaya/betapathogen/src/master/)
  
  - Tutorials:
    1. [Fitting a mixed model for inoculum availability](https://bitbucket.org/joaquin-martinez-minaya/betapathogen/src/master/vignettes/)
    


### 2019
- **Arabidopsis thaliana** 

  - Manuscript: [A hierarchical Bayesian Beta regression approach to study the effects of geographical genetic structure and spatial autocorrelation on species distribution range shifts](https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13024)
  
  - R-Code: [Arabidopsis](http://doi.org/10.5281/zenodo.2552025)
  

</div>

